USE [master]
GO

/****** Object:  Database [BikeStores]    Script Date: 17/06/2021 08:53:14 ******/
CREATE DATABASE [BikeStores]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BikeStores', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\BikeStores.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BikeStores_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\BikeStores_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BikeStores].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BikeStores] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BikeStores] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BikeStores] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BikeStores] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BikeStores] SET ARITHABORT OFF 
GO

ALTER DATABASE [BikeStores] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BikeStores] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BikeStores] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BikeStores] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BikeStores] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BikeStores] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BikeStores] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BikeStores] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BikeStores] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BikeStores] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BikeStores] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BikeStores] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BikeStores] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BikeStores] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BikeStores] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BikeStores] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BikeStores] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BikeStores] SET RECOVERY FULL 
GO

ALTER DATABASE [BikeStores] SET  MULTI_USER 
GO

ALTER DATABASE [BikeStores] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BikeStores] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BikeStores] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BikeStores] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BikeStores] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BikeStores] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BikeStores] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BikeStores] SET  READ_WRITE 
GO

