USE [master]
GO

/****** Object:  Database [BikeStoresDW]    Script Date: 17/06/2021 08:53:38 ******/
CREATE DATABASE [BikeStoresDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BikeStoresDW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\BikeStoresDW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BikeStoresDW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\BikeStoresDW_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BikeStoresDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BikeStoresDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BikeStoresDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BikeStoresDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BikeStoresDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BikeStoresDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [BikeStoresDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BikeStoresDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BikeStoresDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BikeStoresDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BikeStoresDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BikeStoresDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BikeStoresDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BikeStoresDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BikeStoresDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BikeStoresDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BikeStoresDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BikeStoresDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BikeStoresDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BikeStoresDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BikeStoresDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BikeStoresDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BikeStoresDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BikeStoresDW] SET RECOVERY FULL 
GO

ALTER DATABASE [BikeStoresDW] SET  MULTI_USER 
GO

ALTER DATABASE [BikeStoresDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BikeStoresDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BikeStoresDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BikeStoresDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BikeStoresDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BikeStoresDW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BikeStoresDW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BikeStoresDW] SET  READ_WRITE 
GO

